In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
import pickle
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
#Best parameters extraction
# Best model prediction
# How to get accuracy & confusion matrix

In [4]:
dt = DecisionTreeClassifier(random_state=42)

param_grid = {
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_depth': [None, 3, 5, 7, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [5]:
grid = GridSearchCV(estimator=dt,
                    param_grid=param_grid,
                    cv=5,
                    scoring='accuracy',
                    n_jobs=-1)

In [12]:
myDataset.head()

age  weight  height exercise  sleep sugar_intake smoking alcohol married  \
0   56      67     195      low    6.1       medium     yes     yes     yes   
1   69      76     170     high    6.9         high      no      no      no   
2   46     106     153     high    6.6          low     yes      no      no   
3   32      54     186   medium    8.5       medium      no      no      no   
4   60      98     195     high    8.0          low      no      no     yes   

      profession   bmi health_risk  
0  office_worker  17.6        high  
1        teacher  26.3        high  
2         artist  45.3        high  
3         artist  15.6         low  
4        teacher  25.8        high

In [16]:
df.head()

age  weight  height  exercise  sleep  sugar_intake  smoking  alcohol  \
0   56      67     195         1    6.1             2        1        1   
1   69      76     170         0    6.9             0        0        0   
2   46     106     153         0    6.6             1        1        0   
3   32      54     186         2    8.5             2        0        0   
4   60      98     195         0    8.0             1        0        0   

   married  profession   bmi  health_risk  
0        1           5  17.6            0  
1        0           7  26.3            0  
2        0           0  45.3            0  
3        0           0  15.6            1  
4        1           7  25.8            0

In [17]:
myDataset = pd.read_csv("Health_Risk_Prediction.csv")
df = myDataset.copy() 

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

label_columns = ['exercise', 'sugar_intake','profession','smoking','alcohol','married','health_risk']

#df_label = df[label_cols].apply(le.fit_transform)
df_label = df[label_columns].apply(le.fit_transform)
df_numeric = df.select_dtypes(include=['int64', 'float64'])
newdata = pd.concat([df_numeric, df_label,], axis=1)
newdata.drop(['height', 'weight','profession','married'], axis=1, inplace=True)  #Dropping the columns as BMI col uses these values to calculate.
#Adding only the selected Features and dropping the other columns based on efficency and accuracy

indep_X=newdata.drop('health_risk', axis=1)
dep_Y=newdata['health_risk']

In [20]:
dep_Y

0       0
1       0
2       0
3       1
4       0
       ..
4995    1
4996    0
4997    0
4998    1
4999    1
Name: health_risk, Length: 5000, dtype: int32

In [44]:
newdata.head()

age  sleep   bmi  exercise  sugar_intake  profession  smoking  alcohol  \
0   56    6.1  17.6         1             2           5        1        1   
1   69    6.9  26.3         0             0           7        0        0   
2   46    6.6  45.3         0             1           0        1        0   
3   32    8.5  15.6         2             2           0        0        0   
4   60    8.0  25.8         0             1           7        0        0   

   married  health_risk  
0        1            0  
1        0            0  
2        0            0  
3        0            1  
4        1            0

In [18]:
df.tail()

age  weight  height exercise  sleep sugar_intake smoking alcohol  \
4995   42      75     187   medium    7.2          low      no      no   
4996   39      86     183      low    7.4          low      no      no   
4997   48      56     194     none    7.2         high     yes     yes   
4998   34     109     148   medium    9.9       medium      no      no   
4999   72      47     149     high    6.3       medium      no      no   

     married profession   bmi health_risk  
4995     yes     driver  21.4         low  
4996     yes   engineer  25.7        high  
4997     yes   engineer  14.9        high  
4998     yes     doctor  49.8         low  
4999     yes     driver  21.2         low

In [19]:
newdata.tail()

age  sleep   bmi  exercise  sugar_intake  smoking  alcohol  health_risk
4995   42    7.2  21.4         2             1        0        0            1
4996   39    7.4  25.7         1             1        0        0            0
4997   48    7.2  14.9         3             0        1        1            0
4998   34    9.9  49.8         2             2        0        0            1
4999   72    6.3  21.2         0             2        0        0            1

In [48]:
X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.30, random_state = 0)
grid.fit(X_train, y_train)     # <--- REQUIRED

print(grid.best_params_)       # <--- Works now
print(grid.best_score_)        # optional
best_model = grid.best_estimator_

{'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 5}
0.9934285714285714


In [9]:
print("The best Params is:",grid.best_params_)       # <--- Works now
print("The Best score is:",grid.best_score_) 
best_model

The best Params is: {'criterion': 'entropy', 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}
The Best score is: 0.9917142857142858


DecisionTreeClassifier(criterion='entropy', random_state=42)

In [49]:
print("The best Params is:",grid.best_params_)       # <--- Works now
print("The Best score is:",grid.best_score_) 
best_model

The best Params is: {'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 5}
The Best score is: 0.9934285714285714


DecisionTreeClassifier(criterion='entropy', max_depth=10, min_samples_split=5,
                       random_state=42)

In [8]:
print("The best Params is:",grid.best_params_)       # <--- Works now
print("The Best score is:",grid.best_score_) 
best_model

The best Params is: {'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 5}
The Best score is: 0.9928571428571429


DecisionTreeClassifier(criterion='entropy', max_depth=10, min_samples_split=5,
                       random_state=42)

In [50]:
print("The best Params is:",grid.best_params_)       # <--- Works now
print("The Best score is:",grid.best_score_) 
best_model

The best Params is: {'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 5}
The Best score is: 0.9934285714285714


DecisionTreeClassifier(criterion='entropy', max_depth=10, min_samples_split=5,
                       random_state=42)

#FINAL BEST MOEDL


In [15]:
#HOW TO MAKE PREDICTION

In [51]:
y_pred = best_model.predict(X_test)


In [52]:
y_pred

array([0, 0, 0, ..., 1, 1, 1])

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9946666666666667
Confusion Matrix:
 [[1046    2]
 [   6  446]]
Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00      1048
           1       1.00      0.99      0.99       452

    accuracy                           0.99      1500
   macro avg       0.99      0.99      0.99      1500
weighted avg       0.99      0.99      0.99      1500



In [53]:
#Final Best Moedl
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.996
Confusion Matrix:
 [[1047    1]
 [   5  447]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1048
           1       1.00      0.99      0.99       452

    accuracy                           1.00      1500
   macro avg       1.00      0.99      1.00      1500
weighted avg       1.00      1.00      1.00      1500



In [54]:
#model = DecisionTreeClassifier().fit(X_train, y_train)

# Save
import joblib
joblib.dump(best_model, "decision_tree.pkl")

# Load
loaded_model = joblib.load("decision_tree.pkl")

# Predict
prediction = loaded_model.predict(X_test)

In [55]:
newdata.columns

Index(['age', 'sleep', 'bmi', 'exercise', 'sugar_intake', 'smoking', 'alcohol',
       'health_risk'],
      dtype='object')

In [56]:
prediction

array([0, 0, 0, ..., 1, 1, 1])

In [57]:
newdata.shape

(5000, 8)

In [59]:
## Provide Input and Predict
import numpy as np

# Load your saved model
loaded_model = joblib.load("decision_tree.pkl")

# Enter the input values - Features 
a = float(input("Enter value for age: "))
b = float(input("Enter value for sleep: "))
c = float(input("Enter value for bmi: "))
d = float(input("Enter value for excersie: "))
e = float(input("Enter value for sugar_intake: "))
f = float(input("Enter value for smoking: "))
g = float(input("Enter value for alcohol: "))


# Combine input into array
user_data = np.array([[a, b,c,d,e,f,g]])

# Predict
prediction = loaded_model.predict(user_data)

print("The Health Risk is (0=low, 1=high):", prediction[0])

Enter value for age:  65
Enter value for sleep:  4.4
Enter value for bmi:  36.6
Enter value for excersie:  1
Enter value for sugar_intake:  2
Enter value for smoking:  1
Enter value for alcohol:  1


The Health Risk is (0=low, 1=high): 0


C:\Anaconda\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [60]:
X_test

age  sleep   bmi  exercise  sugar_intake  smoking  alcohol
398    65    4.4  36.6         1             2        1        1
3833   68    5.5  35.3         2             2        0        0
4836   67    7.2  17.5         1             2        0        0
4572   57    6.8  17.8         1             2        1        0
636    31    4.6  19.8         1             2        0        0
...   ...    ...   ...       ...           ...      ...      ...
4554   35    8.0  50.2         2             2        0        0
4807   58    7.1  26.9         0             1        0        0
1073   40    5.9  15.6         2             2        0        0
2906   25    9.1  23.7         0             2        1        0
1357   22    6.9  21.6         2             2        0        0

[1500 rows x 7 columns]

In [62]:
# Enter the input values - Features 
# Enter the input values - Features 
a = float(input("Enter value for age: "))
b = float(input("Enter value for sleep: "))
c = float(input("Enter value for bmi: "))
d = float(input("Enter value for excersie: "))
e = float(input("Enter value for sugar_intake: "))
f = float(input("Enter value for smoking: "))
g = float(input("Enter value for alcohol: "))


# Combine input into array
user_data = np.array([[a, b,c,d,e,f,g]])

# Predict
prediction = loaded_model.predict(user_data)

print("The Health Risk is (0=low, 1=high):", prediction[0])

Enter value for age:  35
Enter value for sleep:  8
Enter value for bmi:  50.2
Enter value for excersie:  2
Enter value for sugar_intake:  2
Enter value for smoking:  0
Enter value for alcohol:  0


The Health Risk is (0=low, 1=high): 1


C:\Anaconda\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [61]:
y_test

398     0
3833    0
4836    0
4572    0
636     1
       ..
4554    1
4807    0
1073    1
2906    1
1357    1
Name: health_risk, Length: 1500, dtype: int64

In [63]:
import pickle  #library to save the model
file_name = "DT_Class_FinalModel.sav"
pickle.dump(grid,open(file_name,'wb'))

In [64]:
import pickle

load_model = pickle.load(open("DT_Class_FinalModel.sav",'rb'))  #Read Binary from the file  

In [67]:
#Predict the output. Enter the input.
R_Output =  load_model.predict([[40,8,20.5,2,1,1,1]])
print(R_Output)

[0]


C:\Anaconda\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [68]:
health_risk_value = df.loc[(df['bmi'] == 50.2) & (df['age'] == 35), 'health_risk'].values[0]
print(health_risk_value)

low


In [69]:
health_risk_value = df.loc[(df['bmi'] == 36.6) & (df['age'] == 65), 'health_risk'].values[0]
print(health_risk_value)

high


## Decode the Input and ouptut for deployment 

In [7]:
encoders = {}

for col in label_columns:
    le_c = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le_c

# save encoders
with open("encoders.sav", "wb") as f:
    pickle.dump(encoders, f)
